########################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
########################
spring:
  config:
    import: optional:file:./samples/,optional:file:./.output/
  profiles:
    active: default
  application:
    name: volt
  output:
    ansi:
      enabled: always
  shell:
    command:
      script:
        enabled: false
    interactive:
      enabled: true
    script:
      enabled: true
    version:
      enabled: true
      showBuildName: true
      showGitBranch: true
    history:
      name: volt.history
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
    deserialization:
      fail_on_unknown_properties: false
      fail_on_ignored_properties: false
    default-property-inclusion: non_null
    locale: en_US
  ##################################
  datasource:
    url: jdbc:postgresql://localhost:26257/volt?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: root
    password:
    hikari:
      auto-commit: true
      maximum-pool-size: 10
      minimum-idle: 0
      initialization-fail-timeout: -1
      connection-timeout: 5000
      catalog: public
      pool-name: volt-pool
      read-only: true
  #############################
  mvc:
    problemdetails:
      enabled: true
#############################
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: env,info,health,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    db:
      enabled: false
  metrics:
    tags:
      application: ${spring.application.name}
##################################
##################################
server:
  port: 8090
#  error:
#    whitelabel:
#      enabled: false
#    include-stacktrace: always
#    include-message: always
#    include-binding-errors: always
#    include-exception: true
  compression:
    enabled: true
    min-response-size: 256
    mime-types: application/octet-stream,application/prs.hal-forms+json,text/plain
##################################
logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) [%t] %clr([%logger{39}]){cyan} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
##################################
application:
  # Default is host vCPUs x 4
  maximum-threads: -1
##################################
model:
  outputPath: ".output"
