spring:
  datasource:
    url: "jdbc:postgresql://localhost:26257/defaultdb?sslmode=disable"
    username: "root"
model:
  options:
    delimiter: ","
    fields_enclosed_by: '(empty)'

  importInto:
    options:
      delimiter: ";"
      fields_enclosed_by: '"'
      allow_quoted_null: "null"
      skip: "1"
    file: "import.sql"
    prefix: "http://${local-ip}:8090/"

  outputPath: ".output"

  tables:
    - name: "customer"
      count: "100"
      columns:
        - name: "id"
          gen:
            type: "sequence"
            from: "1"
            step: 1
        - name: "email"
          expression: "randomEmail()"
        - name: "firstName"
          expression: "randomFirstName()"
        - name: "lastName"
          expression: "randomLastName()"
        - name: "password"
          expression: "randomString(128)"
        - name: "address1"
          expression: "randomString(255)"
        - name: "address2"
          expression: "randomString(255)"
        - name: "postcode"
          expression: "randomString(16)"
        - name: "city"
          expression: "randomCity()"
        - name: "country"
          expression: "randomCountry()"
        - name: "updated_at"
          expression: "randomDateTime()"

    - name: "purchase_order"
      columns:
        - name: "id"
          gen:
            type: "sequence"
            from: "1"
            step: 1
        - name: "customer_id"
          each:
            name: "customer"
            column: "id"
            multiplier: 2
        - name: "bill_address1"
          expression: "randomString(255)"
        - name: "bill_address2"
          expression: "randomString(255)"
        - name: "bill_city"
          expression: "randomString(255)"
        - name: "bill_country"
          expression: "randomString(16)"
        - name: "bill_postcode"
          expression: "randomString(16)"
        - name: "bill_to_name"
          expression: "randomString(255)"
        - name: "deliv_address1"
          expression: "randomString(255)"
        - name: "deliv_address2"
          expression: "randomString(255)"
        - name: "deliv_city"
          expression: "randomString(255)"
        - name: "deliv_country"
          expression: "randomString(16)"
        - name: "deliv_postcode"
          expression: "randomString(16)"
        - name: "deliv_to_name"
          expression: "randomString(255)"
        - name: "date_placed"
          expression: "randomDate()"
        - name: "status"
          expression: "randomString(64)"
        - name: "amount"
          expression: "randomBigDecimal(0,100000000000000000,2)"
        - name: "currency"
          expression: "randomCurrency()"
        - name: "version"
          expression: "randomInt()"
    - name: "purchase_order_item"
      columns:
        - name: "order_id"
          each:
            name: "purchase_order"
            column: "id"
            multiplier: 5
        - name: "item_pos"
          gen:
            type: "sequence"
            from: "1"
            to: "5"
            step: 1
        - name: "product_id"
          expression: "randomLong()"
        - name: "quantity"
          expression: "randomInt()"
        - name: "status"
          expression: "randomString(64)"
        - name: "amount"
          expression: "randomBigDecimal(0,100000000000000000,2)"
        - name: "currency"
          expression: "randomCurrency()"
        - name: "weight_kg"
          expression: "randomDouble()"
