model:
  importInto:
    options:
      delimiter: ","
      skip: "1"
      allow_quoted_null: "null"
      fields_enclosed_by: "\""
    file: "import.sql"
    prefix: "http://${local-ip}:8090/"
  outputPath: ".output"

  tables:
    - name: "payment_method"
      count: "10"
      columns:
        - name: "id"
          gen:
            type: "sequence"
            from: "1"
            step: 1
        - name: "payment_type"
          expression: "random('a','b','c','d','e','f')"
        - name: "number"
          expression: "rowNumber()"
        - name: "retailer"
          expression: "randomString(255)"
        - name: "voucher_code"
          expression: "randomString(25)"

    - name: "orders"
      count: "10"
      columns:
        - name: "id"
          gen:
            type: "sequence"
            from: "1"
            step: 1
        - name: "payment_method_id"
          ref:
            name: "payment_method"
            column: "id"
        - name: "payment_type"
          ref:
            name: "payment_method"
            column: "payment_type"
        - name: "currency"
          expression: "randomCurrency()"
        - name: "version"
          expression: "randomInt()"

    - name: "order_item"
      columns:
        - name: "order_id"
          each:
            name: "orders"
            column: "id"
            multiplier: 2
        - name: "item_pos"
          gen:
            type: "sequence"
            from: "1"
            step: 1
        - name: "load_type"
          expression: "randomString(16)"
        - name: "quantity"
          expression: "rowNumber()"
        - name: "status"
          expression: "randomString(64)"
        - name: "amount"
          expression: "randomBigDecimal(0,100000000000000000,2)"
        - name: "weight_kg"
          expression: "randomDouble()"
